sudo: required
services:
  - docker

before_install:
  - docker build -t tkartik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tkartik/react-test npm test -- --coverage

after_success:
  - docker build -t tkartik/multi-client ./client
  - docker build -t tkartik/multi-nginx ./nginx
  - docker build -t tkartik/multi-server ./server
  - docker build -t tkartik/multi-worker ./worker
  - docker login --username "$DOCKER_ID" --password "$DOCKER_PASSWORD" docker.io
  - docker push tkartik/multi-client
  - docker push tkartik/multi-nginx
  - docker push tkartik/multi-server
  - docker push tkartik/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-488940189911'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
